version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@0.0.8

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'amazon-ecs-sample'
          tag: 'app-latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'console-sample-app'
          cluster-name: 'php-cluster'
          service-name: 'php-service'
          container-image-name-updates: 'container=simple-app,tag=app-latest'